### ISSUE TITLE
Change text and title for Hacking projects section

### ISSUE THREAD

**Issue by rajido** [elixir-europe/bh2018paris#10]
Replace text and title in the website. "Process to propose and select Hacking projects" should be renamed to "Hacking projects" since the process to select projects is finished. Text available in the google doc.

**Comment by ricardoaat** [comment]
I have updated the website with the information added on the document. https://github.com/elixir-europe/bh2018paris/commit/966761c83345623623e1cd274958b9ee27859b51

Let me know what you think
