### ISSUE TITLE
Change how we display the programme

### ISSUE THREAD

**Issue by rajido** [elixir-europe/bh2018paris#6]
@Cernoskova says it is confusing to have several columns in the programme because it implies parallel sessions. Better to have just two columns (date + content) even if ti is longer.

It is also confusing for people to know what time the BH starts. We should have the collocated meeting s in a separate place. For instance below the BH programme. We could call this new section Collocated meetings.

At the moment we have two files for the programme. It might also be confusing for people to know which to update. Remove one if it is not needed, otherwise rename? https://github.com/elixir-europe/bh2018paris/tree/master/_programmes

**Comment by ricardoaat** [comment]
Hello @rajido @Cernoskova ,
I have created a new [branch](https://github.com/elixir-europe/bh2018paris/tree/ric/feat/programme-lookNfeel-improvement) with a new Programme version. 

Please give it a look and tell me what you think.

Kind regards,
Ricardo Arcila

**Comment by rajido** [comment]
Made minor changes. Looks good. Please feel free to merge. thanks, rafa.
