### ISSUE TITLE
Add new hacking topics

### ISSUE THREAD

**Issue by rajido** [elixir-europe/bh2018paris#9]
Add new hacking topics to the [website](http://bh2018paris.info/projects) and to the the [github repo](https://github.com/elixir-europe/BioHackathon).

Topic | Platform | ID | Title
-- | -- | -- | --
Workflows | tools | 19 | Enrichment and propagation of metagenomic experimental metadata.
Workflows | tools | 20 | Improve Shiny and RStudio integration within Galaxy using Galaxy Interactive Environment
Training materials | training | 21 | Assessing the FAIRness of Training Materials
Data distribution | interoperability | 22 | Deposition of Research Assets between FAIRDOM SEEK's and other public deposition services
Data integration | interoperability | 23 | Application of RDF-based models and tools for enhancing interoperable use of biomedical resources
Structure metadata | interoperability | 24 | Putting structured data into individual entry pages in biological database
Data integration | interoperability | 25 | ProtVista (protein annotation viewer) extension using Bioschemas data
Identifiers | interoperability | 26 | Using blockchain in biomedical provenance, the identifiers use case.
Workflows | Tools | 27 | Import workflows into TeSS Concept Maps
Structured metadata | interoperability | 28 | From Biotea to Bioschemas: definition of profiles required to represent scholarly publications
Data integration | interoperability | 29 | Pathway effect prediction for protein targets

**Comment by ricardoaat** [comment]
These Hacking Projects has just been added to the website, I have also created the folders for each project on the BioHackathon repository. Just missing the README.md file information for them. Please give it a look and tell me what you think. https://github.com/elixir-europe/bh2018paris/commit/966761c83345623623e1cd274958b9ee27859b51
